input {
  beats {
    port => 5044
  }
}

filter {
  if [agent][type] == "winlogbeat" {
    mutate { add_tag => ["windows", "winlogbeat"] }
  }
  
  if [agent][type] == "filebeat" {
    mutate { add_tag => ["linux", "filebeat"] }
  }

  # Parse SSH failed password attempts from auth.log
  if [log][file][path] == "/var/log/auth.log" {
    grok {
      match => {
        "message" => "%{SYSLOGTIMESTAMP:syslog.timestamp} %{HOSTNAME:observed.hostname} sshd\[%{NUMBER:process.pid}\]: Failed password for %{USER:user.name} from %{IP:source.ip} port %{NUMBER:source.port:int} %{WORD:network.transport}"
      }
      tag_on_failure => ["_grokparsefailure_sshd"]
    }

    mutate {
      add_field => {
        "event.category" => "authentication"
        "event.type"     => "start"
        "event.outcome"  => "failure"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["https://192.168.53.40:9200"]
    ssl => true
    ssl_certificate_verification => false
    user => "elastic"
    password => "elastic"
    index => "lab-logs-%{+YYYY.MM.dd}"
  }
}
